export default class MessageEntityType {
  static MENTION = 'mention'
  static HASHTAG = 'hashtag'
  static CASHTAG = 'cashtag'
  static BOT_COMMAND = 'bot_command'
  static URL = 'url'
  static EMAIL = 'email'
  static PHONE_NUMBER = 'phone_number'
  static BOLD = 'bold'
  static ITALIC = 'italic'
  static UNDERLINE = 'underline'
  static STRIKETHROUGH = 'strikethrough'
  static CODE = 'code'
  static PRE = 'pre'
  static TEXT_LINK = 'text_link'
  static TEXT_MENTION = 'text_mention'
}
