const GetUpdatesRequest = require('./GetUpdatesRequest')
const SetWebhookRequest = require('./SetWebhookRequest')
const DeleteWebhookRequest = require('./DeleteWebhookRequest')
const GetWebhookInfoRequest = require('./GetWebhookInfoRequest')
const GetMeRequest = require('./GetMeRequest')
const LogOutRequest = require('./LogOutRequest')
const CloseRequest = require('./CloseRequest')
const SendMessageRequest = require('./SendMessageRequest')
const ForwardMessageRequest = require('./ForwardMessageRequest')
const CopyMessageRequest = require('./CopyMessageRequest')
const SendPhotoRequest = require('./SendPhotoRequest')
const SendAudioRequest = require('./SendAudioRequest')
const SendDocumentRequest = require('./SendDocumentRequest')
const SendVideoRequest = require('./SendVideoRequest')
const SendAnimationRequest = require('./SendAnimationRequest')
const SendVoiceRequest = require('./SendVoiceRequest')
const SendVideoNoteRequest = require('./SendVideoNoteRequest')
const SendMediaGroupRequest = require('./SendMediaGroupRequest')
const SendLocationRequest = require('./SendLocationRequest')
const EditMessageLiveLocationRequest = require('./EditMessageLiveLocationRequest')
const StopMessageLiveLocationRequest = require('./StopMessageLiveLocationRequest')
const SendVenueRequest = require('./SendVenueRequest')
const SendContactRequest = require('./SendContactRequest')
const SendPollRequest = require('./SendPollRequest')
const SendDiceRequest = require('./SendDiceRequest')
const SendChatActionRequest = require('./SendChatActionRequest')
const GetUserProfilePhotosRequest = require('./GetUserProfilePhotosRequest')
const GetFileRequest = require('./GetFileRequest')
const DownloadFileByPathRequest = require('./DownloadFileByPathRequest')
const KickChatMemberRequest = require('./KickChatMemberRequest')
const UnbanChatMemberRequest = require('./UnbanChatMemberRequest')
const RestrictChatMemberRequest = require('./RestrictChatMemberRequest')
const PromoteChatMemberRequest = require('./PromoteChatMemberRequest')
const SetChatAdminCustomTitleRequest = require('./SetChatAdminCustomTitleRequest')
const SetChatPermissionsRequest = require('./SetChatPermissionsRequest')
const ExportChatInviteLinkRequest = require('./ExportChatInviteLinkRequest')
const SetChatPhotoRequest = require('./SetChatPhotoRequest')
const DeleteChatPhotoRequest = require('./DeleteChatPhotoRequest')
const SetChatTitleRequest = require('./SetChatTitleRequest')
const SetChatDescriptionRequest = require('./SetChatDescriptionRequest')
const PinChatMessageRequest = require('./PinChatMessageRequest')
const UnpinChatMessageRequest = require('./UnpinChatMessageRequest')
const UnpinAllChatMessagesRequest = require('./UnpinAllChatMessagesRequest')
const LeaveChatRequest = require('./LeaveChatRequest')
const GetChatRequest = require('./GetChatRequest')
const GetChatAdminsRequest = require('./GetChatAdminsRequest')
const GetChatMembersCountRequest = require('./GetChatMembersCountRequest')
const GetChatMemberRequest = require('./GetChatMemberRequest')
const SetChatStickerSetRequest = require('./SetChatStickerSetRequest')
const DeleteChatStickerSetRequest = require('./DeleteChatStickerSetRequest')
const AnswerCallbackQueryRequest = require('./AnswerCallbackQueryRequest')
const SetMyCommandsRequest = require('./SetMyCommandsRequest')
const GetMyCommandsRequest = require('./GetMyCommandsRequest')
const EditMessageTextRequest = require('./EditMessageTextRequest')
const EditMessageCaptionRequest = require('./EditMessageCaptionRequest')
const EditMessageMediaRequest = require('./EditMessageMediaRequest')
const EditMessageReplyMarkupRequest = require('./EditMessageReplyMarkupRequest')
const StopPollRequest = require('./StopPollRequest')
const DeleteMessageRequest = require('./DeleteMessageRequest')
const SendStickerRequest = require('./SendStickerRequest')
const GetStickerSetRequest = require('./GetStickerSetRequest')
const UploadStickerFileRequest = require('./UploadStickerFileRequest')
const CreateNewStickerSetRequest = require('./CreateNewStickerSetRequest')
const AddStickerToSetRequest = require('./AddStickerToSetRequest')
const SetStickerPositionInSetRequest = require('./SetStickerPositionInSetRequest')
const DeleteStickerFromSetRequest = require('./DeleteStickerFromSetRequest')
const SetStickerSetThumbRequest = require('./SetStickerSetThumbRequest')
const AnswerInlineQueryRequest = require('./AnswerInlineQueryRequest')
const SendInvoiceRequest = require('./SendInvoiceRequest')
const AnswerShippingQueryRequest = require('./AnswerShippingQueryRequest')
const AnswerPreCheckoutQueryRequest = require('./AnswerPreCheckoutQueryRequest')
const SetPassportDataErrorsRequest = require('./SetPassportDataErrorsRequest')
const SendGameRequest = require('./SendGameRequest')
const SetGameScoreRequest = require('./SetGameScoreRequest')
const GetGameHighScoresRequest = require('./GetGameHighScoresRequest')

class Requests {}
Requests.GetUpdatesRequest = GetUpdatesRequest
Requests.SetWebhookRequest = SetWebhookRequest
Requests.DeleteWebhookRequest = DeleteWebhookRequest
Requests.GetWebhookInfoRequest = GetWebhookInfoRequest
Requests.GetMeRequest = GetMeRequest
Requests.LogOutRequest = LogOutRequest
Requests.CloseRequest = CloseRequest
Requests.SendMessageRequest = SendMessageRequest
Requests.ForwardMessageRequest = ForwardMessageRequest
Requests.CopyMessageRequest = CopyMessageRequest
Requests.SendPhotoRequest = SendPhotoRequest
Requests.SendAudioRequest = SendAudioRequest
Requests.SendDocumentRequest = SendDocumentRequest
Requests.SendVideoRequest = SendVideoRequest
Requests.SendAnimationRequest = SendAnimationRequest
Requests.SendVoiceRequest = SendVoiceRequest
Requests.SendVideoNoteRequest = SendVideoNoteRequest
Requests.SendMediaGroupRequest = SendMediaGroupRequest
Requests.SendLocationRequest = SendLocationRequest
Requests.EditMessageLiveLocationRequest = EditMessageLiveLocationRequest
Requests.StopMessageLiveLocationRequest = StopMessageLiveLocationRequest
Requests.SendVenueRequest = SendVenueRequest
Requests.SendContactRequest = SendContactRequest
Requests.SendPollRequest = SendPollRequest
Requests.SendDiceRequest = SendDiceRequest
Requests.SendChatActionRequest = SendChatActionRequest
Requests.GetUserProfilePhotosRequest = GetUserProfilePhotosRequest
Requests.GetFileRequest = GetFileRequest
Requests.DownloadFileByPathRequest = DownloadFileByPathRequest
Requests.KickChatMemberRequest = KickChatMemberRequest
Requests.UnbanChatMemberRequest = UnbanChatMemberRequest
Requests.RestrictChatMemberRequest = RestrictChatMemberRequest
Requests.PromoteChatMemberRequest = PromoteChatMemberRequest
Requests.SetChatAdminCustomTitleRequest = SetChatAdminCustomTitleRequest
Requests.SetChatPermissionsRequest = SetChatPermissionsRequest
Requests.ExportChatInviteLinkRequest = ExportChatInviteLinkRequest
Requests.SetChatPhotoRequest = SetChatPhotoRequest
Requests.DeleteChatPhotoRequest = DeleteChatPhotoRequest
Requests.SetChatTitleRequest = SetChatTitleRequest
Requests.SetChatDescriptionRequest = SetChatDescriptionRequest
Requests.PinChatMessageRequest = PinChatMessageRequest
Requests.UnpinChatMessageRequest = UnpinChatMessageRequest
Requests.UnpinAllChatMessagesRequest = UnpinAllChatMessagesRequest
Requests.LeaveChatRequest = LeaveChatRequest
Requests.GetChatRequest = GetChatRequest
Requests.GetChatAdminsRequest = GetChatAdminsRequest
Requests.GetChatMembersCountRequest = GetChatMembersCountRequest
Requests.GetChatMemberRequest = GetChatMemberRequest
Requests.SetChatStickerSetRequest = SetChatStickerSetRequest
Requests.DeleteChatStickerSetRequest = DeleteChatStickerSetRequest
Requests.AnswerCallbackQueryRequest = AnswerCallbackQueryRequest
Requests.SetMyCommandsRequest = SetMyCommandsRequest
Requests.GetMyCommandsRequest = GetMyCommandsRequest
Requests.EditMessageTextRequest = EditMessageTextRequest
Requests.EditMessageCaptionRequest = EditMessageCaptionRequest
Requests.EditMessageMediaRequest = EditMessageMediaRequest
Requests.EditMessageReplyMarkupRequest = EditMessageReplyMarkupRequest
Requests.StopPollRequest = StopPollRequest
Requests.DeleteMessageRequest = DeleteMessageRequest
Requests.SendStickerRequest = SendStickerRequest
Requests.GetStickerSetRequest = GetStickerSetRequest
Requests.UploadStickerFileRequest = UploadStickerFileRequest
Requests.CreateNewStickerSetRequest = CreateNewStickerSetRequest
Requests.AddStickerToSetRequest = AddStickerToSetRequest
Requests.SetStickerPositionInSetRequest = SetStickerPositionInSetRequest
Requests.DeleteStickerFromSetRequest = DeleteStickerFromSetRequest
Requests.SetStickerSetThumbRequest = SetStickerSetThumbRequest
Requests.AnswerInlineQueryRequest = AnswerInlineQueryRequest
Requests.SendInvoiceRequest = SendInvoiceRequest
Requests.AnswerShippingQueryRequest = AnswerShippingQueryRequest
Requests.AnswerPreCheckoutQueryRequest = AnswerPreCheckoutQueryRequest
Requests.SetPassportDataErrorsRequest = SetPassportDataErrorsRequest
Requests.SendGameRequest = SendGameRequest
Requests.SetGameScoreRequest = SetGameScoreRequest
Requests.GetGameHighScoresRequest = GetGameHighScoresRequest

module.exports = Requests
