const Response = require('./Response')
const ResponseParameters = require('./ResponseParameters')
const Update = require('./Update')
const WebhookInfo = require('./WebhookInfo')
const User = require('./User')
const Chat = require('./Chat')
const Message = require('./Message')
const MessageId = require('./MessageId')
const MessageReply = require('./MessageReply')
const MessageEntity = require('./MessageEntity')
const PhotoSize = require('./PhotoSize')
const Animation = require('./Animation')
const Audio = require('./Audio')
const Document = require('./Document')
const Video = require('./Video')
const VideoNote = require('./VideoNote')
const Voice = require('./Voice')
const Contact = require('./Contact')
const Dice = require('./Dice')
const PollOption = require('./PollOption')
const PollAnswer = require('./PollAnswer')
const Poll = require('./Poll')
const Location = require('./Location')
const Venue = require('./Venue')
const ProximityAlertTriggered = require('./ProximityAlertTriggered')
const UserProfilePhotos = require('./UserProfilePhotos')
const File = require('./File')
const ReplyKeyboardMarkup = require('./ReplyKeyboardMarkup')
const Keyboard = require('./Keyboard')
const KeyboardButton = require('./KeyboardButton')
const KeyboardButtonPollType = require('./KeyboardButtonPollType')
const ReplyKeyboardRemove = require('./ReplyKeyboardRemove')
const InlineKeyboardMarkup = require('./InlineKeyboardMarkup')
const InlineKeyboard = require('./InlineKeyboard')
const InlineKeyboardButton = require('./InlineKeyboardButton')
const LoginUrl = require('./LoginUrl')
const CallbackQuery = require('./CallbackQuery')
const ForceReply = require('./ForceReply')
const ChatPhoto = require('./ChatPhoto')
const ChatMember = require('./ChatMember')
const ChatPermissions = require('./ChatPermissions')
const ChatLocation = require('./ChatLocation')
const BotCommand = require('./BotCommand')
const InputMedia = require('./InputMedia')
const InputMediaPhoto = require('./InputMediaPhoto')
const InputMediaVideo = require('./InputMediaVideo')
const InputMediaAnimation = require('./InputMediaAnimation')
const InputMediaAudio = require('./InputMediaAudio')
const InputMediaDocument = require('./InputMediaDocument')
const InputFile = require('./InputFile')
const Sticker = require('./Sticker')
const StickerSet = require('./StickerSet')
const MaskPosition = require('./MaskPosition')
const InlineQuery = require('./InlineQuery')
const InlineQueryResult = require('./InlineQueryResult')
const InlineQueryResultArticle = require('./InlineQueryResultArticle')
const InlineQueryResultPhoto = require('./InlineQueryResultPhoto')
const InlineQueryResultGif = require('./InlineQueryResultGif')
const InlineQueryResultMpeg4Gif = require('./InlineQueryResultMpeg4Gif')
const InlineQueryResultVideo = require('./InlineQueryResultVideo')
const InlineQueryResultAudio = require('./InlineQueryResultAudio')
const InlineQueryResultVoice = require('./InlineQueryResultVoice')
const InlineQueryResultDocument = require('./InlineQueryResultDocument')
const InlineQueryResultLocation = require('./InlineQueryResultLocation')
const InlineQueryResultVenue = require('./InlineQueryResultVenue')
const InlineQueryResultContact = require('./InlineQueryResultContact')
const InlineQueryResultGame = require('./InlineQueryResultGame')
const InlineQueryResultCachedPhoto = require('./InlineQueryResultCachedPhoto')
const InlineQueryResultCachedGif = require('./InlineQueryResultCachedGif')
const InlineQueryResultCachedMpeg4Gif = require('./InlineQueryResultCachedMpeg4Gif')
const InlineQueryResultCachedSticker = require('./InlineQueryResultCachedSticker')
const InlineQueryResultCachedDocument = require('./InlineQueryResultCachedDocument')
const InlineQueryResultCachedVideo = require('./InlineQueryResultCachedVideo')
const InlineQueryResultCachedVoice = require('./InlineQueryResultCachedVoice')
const InlineQueryResultCachedAudio = require('./InlineQueryResultCachedAudio')
const InputMessageContent = require('./InputMessageContent')
const InputTextMessageContent = require('./InputTextMessageContent')
const InputLocationMessageContent = require('./InputLocationMessageContent')
const InputVenueMessageContent = require('./InputVenueMessageContent')
const InputContactMessageContent = require('./InputContactMessageContent')
const ChosenInlineResult = require('./ChosenInlineResult')
const LabeledPrice = require('./LabeledPrice')
const Invoice = require('./Invoice')
const ShippingAddress = require('./ShippingAddress')
const OrderInfo = require('./OrderInfo')
const ShippingOption = require('./ShippingOption')
const SuccessfulPayment = require('./SuccessfulPayment')
const ShippingQuery = require('./ShippingQuery')
const PreCheckoutQuery = require('./PreCheckoutQuery')
const PassportData = require('./PassportData')
const PassportFile = require('./PassportFile')
const EncryptedPassportElement = require('./EncryptedPassportElement')
const EncryptedCredentials = require('./EncryptedCredentials')
const PassportElementError = require('./PassportElementError')
const PassportElementErrorDataField = require('./PassportElementErrorDataField')
const PassportElementErrorFrontSide = require('./PassportElementErrorFrontSide')
const PassportElementErrorReverseSide = require('./PassportElementErrorReverseSide')
const PassportElementErrorSelfie = require('./PassportElementErrorSelfie')
const PassportElementErrorFile = require('./PassportElementErrorFile')
const PassportElementErrorFiles = require('./PassportElementErrorFiles')
const PassportElementErrorTranslationFile = require('./PassportElementErrorTranslationFile')
const PassportElementErrorTranslationFiles = require('./PassportElementErrorTranslationFiles')
const PassportElementErrorUnspecified = require('./PassportElementErrorUnspecified')
const Game = require('./Game')
const CallbackGame = require('./CallbackGame')
const GameHighScore = require('./GameHighScore')
const FormattedText = require('./FormattedText')
const MarkdownText = require('./MarkdownText')
const MarkdownV2Text = require('./MarkdownV2Text')
const HtmlText = require('./HtmlText')

class Types {}
Types.Response = Response
Types.ResponseParameters = ResponseParameters
Types.Update = Update
Types.WebhookInfo = WebhookInfo
Types.User = User
Types.Chat = Chat
Types.Message = Message
Types.MessageId = MessageId
Types.MessageReply = MessageReply
Types.MessageEntity = MessageEntity
Types.PhotoSize = PhotoSize
Types.Animation = Animation
Types.Audio = Audio
Types.Document = Document
Types.Video = Video
Types.VideoNote = VideoNote
Types.Voice = Voice
Types.Contact = Contact
Types.Dice = Dice
Types.PollOption = PollOption
Types.PollAnswer = PollAnswer
Types.Poll = Poll
Types.Location = Location
Types.Venue = Venue
Types.ProximityAlertTriggered = ProximityAlertTriggered
Types.UserProfilePhotos = UserProfilePhotos
Types.File = File
Types.ReplyKeyboardMarkup = ReplyKeyboardMarkup
Types.Keyboard = Keyboard
Types.KeyboardButton = KeyboardButton
Types.KeyboardButtonPollType = KeyboardButtonPollType
Types.ReplyKeyboardRemove = ReplyKeyboardRemove
Types.InlineKeyboardMarkup = InlineKeyboardMarkup
Types.InlineKeyboard = InlineKeyboard
Types.InlineKeyboardButton = InlineKeyboardButton
Types.LoginUrl = LoginUrl
Types.CallbackQuery = CallbackQuery
Types.ForceReply = ForceReply
Types.ChatPhoto = ChatPhoto
Types.ChatMember = ChatMember
Types.ChatPermissions = ChatPermissions
Types.ChatLocation = ChatLocation
Types.BotCommand = BotCommand
Types.InputMedia = InputMedia
Types.InputMediaPhoto = InputMediaPhoto
Types.InputMediaVideo = InputMediaVideo
Types.InputMediaAnimation = InputMediaAnimation
Types.InputMediaAudio = InputMediaAudio
Types.InputMediaDocument = InputMediaDocument
Types.InputFile = InputFile
Types.Sticker = Sticker
Types.StickerSet = StickerSet
Types.MaskPosition = MaskPosition
Types.InlineQuery = InlineQuery
Types.InlineQueryResult = InlineQueryResult
Types.InlineQueryResultArticle = InlineQueryResultArticle
Types.InlineQueryResultPhoto = InlineQueryResultPhoto
Types.InlineQueryResultGif = InlineQueryResultGif
Types.InlineQueryResultMpeg4Gif = InlineQueryResultMpeg4Gif
Types.InlineQueryResultVideo = InlineQueryResultVideo
Types.InlineQueryResultAudio = InlineQueryResultAudio
Types.InlineQueryResultVoice = InlineQueryResultVoice
Types.InlineQueryResultDocument = InlineQueryResultDocument
Types.InlineQueryResultLocation = InlineQueryResultLocation
Types.InlineQueryResultVenue = InlineQueryResultVenue
Types.InlineQueryResultContact = InlineQueryResultContact
Types.InlineQueryResultGame = InlineQueryResultGame
Types.InlineQueryResultCachedPhoto = InlineQueryResultCachedPhoto
Types.InlineQueryResultCachedGif = InlineQueryResultCachedGif
Types.InlineQueryResultCachedMpeg4Gif = InlineQueryResultCachedMpeg4Gif
Types.InlineQueryResultCachedSticker = InlineQueryResultCachedSticker
Types.InlineQueryResultCachedDocument = InlineQueryResultCachedDocument
Types.InlineQueryResultCachedVideo = InlineQueryResultCachedVideo
Types.InlineQueryResultCachedVoice = InlineQueryResultCachedVoice
Types.InlineQueryResultCachedAudio = InlineQueryResultCachedAudio
Types.InputMessageContent = InputMessageContent
Types.InputTextMessageContent = InputTextMessageContent
Types.InputLocationMessageContent = InputLocationMessageContent
Types.InputVenueMessageContent = InputVenueMessageContent
Types.InputContactMessageContent = InputContactMessageContent
Types.ChosenInlineResult = ChosenInlineResult
Types.LabeledPrice = LabeledPrice
Types.Invoice = Invoice
Types.ShippingAddress = ShippingAddress
Types.OrderInfo = OrderInfo
Types.ShippingOption = ShippingOption
Types.SuccessfulPayment = SuccessfulPayment
Types.ShippingQuery = ShippingQuery
Types.PreCheckoutQuery = PreCheckoutQuery
Types.PassportData = PassportData
Types.PassportFile = PassportFile
Types.EncryptedPassportElement = EncryptedPassportElement
Types.EncryptedCredentials = EncryptedCredentials
Types.PassportElementError = PassportElementError
Types.PassportElementErrorDataField = PassportElementErrorDataField
Types.PassportElementErrorFrontSide = PassportElementErrorFrontSide
Types.PassportElementErrorReverseSide = PassportElementErrorReverseSide
Types.PassportElementErrorSelfie = PassportElementErrorSelfie
Types.PassportElementErrorFile = PassportElementErrorFile
Types.PassportElementErrorFiles = PassportElementErrorFiles
Types.PassportElementErrorTranslationFile = PassportElementErrorTranslationFile
Types.PassportElementErrorTranslationFiles = PassportElementErrorTranslationFiles
Types.PassportElementErrorUnspecified = PassportElementErrorUnspecified
Types.Game = Game
Types.CallbackGame = CallbackGame
Types.GameHighScore = GameHighScore
Types.FormattedText = FormattedText
Types.MarkdownText = MarkdownText
Types.MarkdownV2Text = MarkdownV2Text
Types.HtmlText = HtmlText

module.exports = Types
